server:
  port: 8092

info:
  app:
    name: ${spring.application.name}  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka
  instance:
    prefer-ip-address: true
    appname: qa-service

spring:
  application:
    name: qa-service
  datasource:
    url: jdbc:mysql://localhost:3306/${pts.database.schema-name}?createDatabaseIfNotExist=true&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      naming_strategy: org.hibernate.cfg.DefaultNamingStrategy
    hikari:
      maximum-pool-size: 2  
    open-in-view: false
    properties:
      hibernate:
        default_schema: ${pts.database.schema-name}
        jdbc:
          lob:
            non_contextual_creation: true
  liquibase:
    change-log: classpath:liquibase/changelog-master.xml
    default-schema: ${pts.database.schema-name}
  profiles:
    active: local
  main:
    allow-circular-references: true #TODO: added to avoid problem when migrate qa to new structure
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER    
springdoc:
  api-docs:
    path: /api-docs
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include : '*'
  info:
    env:
      enabled: true
 
pts:
  database:
    schema-name: pts_qa
  log:
    path: ./logs
  pts-core:
    base-url:  http://192.168.0.78:8085/services
ptsqa:
  sec:
    jwtSecret: jwtGrokonezSecretKey
    jwtExpiration: 86400
---
spring:
  config:
    activate:
      on-profile: local
#  jpa:
#    show-sql: true
server:
  tomcat:
    accesslog:
      enabled: true
    basedir: tomcat

logging:
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSS
  level:
    com.zaxxer.hikari: TRACE
    com.zaxxer.hikari.HikariConfig: DEBUG    